parameters:
  # Max file size in Kbs
  max_file_size: '2M'
services:
  _defaults:
    autowire: true
    autoconfigure: true

  # Vault BC services
  Witrac\Vault\:
    resource: '../../../src/Vault'

  # Vault BC controllers
  App\Vault\Controller\:
    resource: '../../../app/Vault/Controller/**'
    tags: [ 'controller.service_arguments' ]

  # Filesystem
  Witrac\Shared\Domain\Filesystem\Filesystem: '@Witrac\Vault\Infrastructure\Filesystem\S3Filesystem'

  # Commands
  Witrac\Vault\Application\Command\:
    resource: '../../../src/Vault/Application/Command/**/**/*Handler.php'
    tags: [ 'witrac.command_handler']

  # AWS S3 Adapter
  Aws\S3\S3Client:
    arguments:
      - version: 'latest'
        region: ''
        endpoint: '%env(S3_ENDPOINT)%'
        use_path_style_endpoint: true
        credentials: false